---

- hosts: all
  become: true
  tasks:

  - name: Create PHP info file
    copy:
        content: <?php phpinfo(); ?>
        dest: /var/www/html/info.php

  - name: Restart httpd
    service:
      name: httpd
      state: restarted
  