---

- hosts: all
  become: true
  tasks:

  - name: Update DNF repo
    dnf:
      update_cache: true
      
  - name: Install apache
    dnf: 
      name: httpd
      state: latest

  - name: Enable and start httpd
    systemd:
      name: httpd
      enabled: true
      state: started

  - name: Test Apache 
    command: httpd -v
    register: apache_version

  - name: Output apache apache_version
    debug:
      msg: "Apache version is {{apache_version}}"