---

- hosts: all
  become: true
  tasks:

  - name: Update DNF repo
    dnf:
      update_cache: true
      
  - name: Install apache
    dnf: 
      name: httpd
      state: latest
    
  - name: Add php package to apache
    dnf:
      name: php

  - name: Enable and start httpd
    service:
      name: httpd
      enabled: true
      state: started

  - name: Test Apache 
    command: httpd -v
    register: apache_version

  - name: Output apache apache_version
    debug:
      msg: "Apache version is {{ apache_version.stdout }}"